name: tmdb
description: "Aplicativo para apresentar lista de filmes de acordo com o site https://www.themoviedb.org/"

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  mobx: ^2.2.0
  flutter_mobx: ^2.0.6+5
  flutter_modular: ^5.0.3
  get_it: ^7.2.0
  intl: ^0.18.1
  sizer: ^2.0.13
  flutter_svg: ^2.0.5
  flutter_animate: ^4.1.0
  dio: ^5.2.1+1
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  analyzer: ^6.4.1
  mobx_codegen: ^2.0.7
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.1.0
  google_fonts: ^4.0.3
  mocktail: ^1.0.3
  modular_test: ^2.0.0
  faker: ^2.1.0
  build_runner: ^2.3.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/core/design/assets/images/laucher_icon.png "

flutter:
  uses-material-design: true
  assets:
    - lib/core/design/assets/icons/
    - lib/core/design/assets/images/

flutter_intl:
  enabled: true
  main_locale: pt_BR